# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'

baseurl = "https://namanlakhwani.dev"
title = "Naman Lakhwani"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

disqusShortname = "Naman"

[params]
    author = "Naman Lakhwani"
    info = [
    "Software Engineer | Hustler",
    "",
    "Master's from IIIT Gwalior",
    "",
    "Go | Kubernetes | Distributed Systems",
    "Master of None",
]
#    info = "Ex: VMware • Mercari Japan • GSoC @CNCF • LFX @Kubernetes"
    description = "Naman Lakhwani's personal website"
    keywords = "naman lakhwani, naman lakhwani blog, naman lakhwani cncf"
    avatarurl = "https://avatars.githubusercontent.com/u/56021229?v=4"

    favicon_32 = "/img/favicon-32x32.png" # TODO
    favicon_16 = "/img/favicon-16x16.png" # TODO

#    footercontent = "SDE • Kubernetes • GoLang • Observability • Distributed systems"

    hidecredits = true
    hidecopyright = false

    rtl = false
    math = true

    dateformat = "January 2, 2006"

    since = 2021

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # # Custom CSS
    # custom_css = []

    # # Custom JS
    # custom_js = []

# Social links
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://linkedin.com/in/naman2001/"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/Namanl2001/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/lakhwani_jii/"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 4
    url = "https://medium.com/@namanlakhwani"
#[[params.social]]
#   name = "Stack Overflow"
#    icon = "fa fa-stack-overflow"
#    weight = 4
#    url = "https://stackoverflow.com/users/12075597/naman-lakhwani?tab=profile"
#[[params.social]]
#   name = "YouTube"
#    icon = "fa fa-youtube"
#    weight = 6
#    url = "https://www.youtube.com/channel/UCKJEOGJw5bbMpORkoRVDDug"
# [[params.social]]
#    name = "RSS"
#    icon = "fa fa-rss"
#    weight = 7
#    url = "https://kakkoyun.me/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "Open-Source"
    weight = 2
    url = "projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "about/"
[[menu.main]]
    name = "Talks"
    weight = 4
    url = "talks/"
# [[menu.main]]
#     name = "CV"
#     weight = 5
#     url = "/cv/"
# [[menu.main]]
#     name = "Stats"
#     weight = 6
#     url = "/stats/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

#[markup]
#  defaultMarkdownHandler = 'blackFriday'
#  [markup.blackFriday]
#    hrefTargetBlank = true
